videos:
  - id: v1_hinglish
    title: "WRITE A PAPER LIKE TOPPERS (Hinglish)"
    url: "https://www.youtube.com/watch?v=MFdRPYQJoDM"
    domain: "Exam startegy"
    declared_code_mix: ["Hindi-English"]

  - id: v2_hindi_iit
    title: "Peridocic table"
    url: "https://www.youtube.com/watch?v=G6h5sAG6sFs"
    domain: "Chemistry"
    declared_code_mix: ["Hindi-English"]

 